#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: bash scripts/validate-epic.sh <epic-directory>

Validates the operational epic profile generated by create-epic for
spec_version 0.5.2. This is stricter than the minimum EPIC core format.
EOF
}

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  usage
  exit 0
fi

if [ "${1:-}" = "" ]; then
  usage
  exit 2
fi

EPIC_DIR=$1

if [ ! -d "$EPIC_DIR" ]; then
  echo "ERROR: epic directory not found: $EPIC_DIR" >&2
  exit 2
fi

EPIC_DIR=$(cd "$EPIC_DIR" && pwd)
EPIC_NAME=$(basename "$EPIC_DIR")

CHECKS=0
PASSED=0
FAILED=0
WARNINGS=0

section() {
  printf '\n%s\n' "$1"
}

pass() {
  CHECKS=$((CHECKS + 1))
  PASSED=$((PASSED + 1))
  printf '  %s %s\n' "PASS" "$1"
}

fail() {
  CHECKS=$((CHECKS + 1))
  FAILED=$((FAILED + 1))
  printf '  %s %s\n' "FAIL" "$1"
}

warn() {
  CHECKS=$((CHECKS + 1))
  WARNINGS=$((WARNINGS + 1))
  printf '  %s %s\n' "WARN" "$1"
}

extract_frontmatter_field() {
  local file=$1
  local field=$2
  awk -v field="$field" '
    NR == 1 && $0 == "---" { in_frontmatter = 1; next }
    in_frontmatter && $0 == "---" { exit }
    in_frontmatter && $0 ~ ("^" field ":") {
      sub("^" field ":[[:space:]]*", "", $0)
      print
      exit
    }
  ' "$file"
}

require_heading() {
  local file=$1
  local heading=$2
  if grep -Eq "^##[[:space:]]+$heading([[:space:]]|$)" "$file"; then
    pass "$file has ## $heading"
  else
    fail "$file is missing ## $heading"
  fi
}

echo "Validating epic: $EPIC_NAME"
echo "Directory: $EPIC_DIR"

section "Name validation"
if [[ "$EPIC_NAME" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]]; then
  pass "Name uses valid characters (lowercase, digits, hyphens)"
else
  fail "Name must use lowercase letters, digits, and hyphens only"
fi

if [ "${#EPIC_NAME}" -le 64 ]; then
  pass "Name length OK (${#EPIC_NAME}/64)"
else
  fail "Name exceeds 64 characters (${#EPIC_NAME}/64)"
fi

if [[ "$EPIC_NAME" == *"--"* ]]; then
  fail "Name must not contain consecutive hyphens"
else
  pass "No consecutive hyphens in name"
fi

section "Required files"
for file in SKILL.md EPIC.md runtime/state.json; do
  if [ -f "$EPIC_DIR/$file" ]; then
    pass "$file exists"
  else
    fail "$file is missing"
  fi
done

section "Runtime layout"
if [ -d "$EPIC_DIR/runtime" ]; then
  pass "runtime exists"
else
  fail "runtime is missing"
fi

for stale in state.json plans log ROADMAP.md DECISIONS.md artifacts; do
  if [ -e "$EPIC_DIR/$stale" ]; then
    fail "Top-level $stale should not exist for the 0.5.2 operational profile"
  fi
done

section "SKILL.md structure"
SKILL_PATH="$EPIC_DIR/SKILL.md"
if [ -f "$SKILL_PATH" ]; then
  NAME_FIELD=$(extract_frontmatter_field "$SKILL_PATH" "name" || true)
  DESCRIPTION_FIELD=$(extract_frontmatter_field "$SKILL_PATH" "description" || true)

  if [ -n "$NAME_FIELD" ]; then
    pass "SKILL.md frontmatter includes name"
  else
    fail "SKILL.md frontmatter is missing name"
  fi

  if [ -n "$DESCRIPTION_FIELD" ]; then
    pass "SKILL.md frontmatter includes description"
  else
    fail "SKILL.md frontmatter is missing description"
  fi

  if grep -Fq "EPIC.md" "$SKILL_PATH"; then
    pass "SKILL.md points readers to EPIC.md"
  else
    fail "SKILL.md should mention EPIC.md as the durable operating context"
  fi

  if grep -Fq "See the **Agent Epics** section below" "$SKILL_PATH"; then
    pass "SKILL.md points first-time readers to the Agent Epics footer"
  else
    warn "SKILL.md should point first-time readers to the Agent Epics footer"
  fi

  if grep -Fq "## Agent Epics" "$SKILL_PATH"; then
    pass "SKILL.md includes the canonical ## Agent Epics footer heading"
  else
    fail "SKILL.md is missing the canonical ## Agent Epics footer heading"
  fi

  if grep -Fq "<!-- epics-canonical-footer: https://raw.githubusercontent.com/agentepics/agentepics/refs/heads/main/footer.md -->" "$SKILL_PATH"; then
    pass "SKILL.md includes the canonical footer marker"
  else
    fail "SKILL.md is missing the canonical footer marker"
  fi

  FOOTER_LINE=$(grep -n '^## Agent Epics$' "$SKILL_PATH" | tail -1 | cut -d: -f1 || true)
  if [ -n "$FOOTER_LINE" ]; then
    AFTER_FOOTER_LINE=$(awk -v start="$FOOTER_LINE" 'NR > start && /^## / { print NR; exit }' "$SKILL_PATH")
    if [ -n "$AFTER_FOOTER_LINE" ]; then
      fail "SKILL.md must not have sections after ## Agent Epics"
    else
      pass "SKILL.md ends with the Agent Epics footer"
    fi
  fi
else
  NAME_FIELD=""
fi

section "EPIC.md frontmatter"
EPIC_PATH="$EPIC_DIR/EPIC.md"
SPEC_VERSION=$(extract_frontmatter_field "$EPIC_PATH" "spec_version" || true)
EPIC_ID=$(extract_frontmatter_field "$EPIC_PATH" "id" || true)

if [ "$SPEC_VERSION" = "0.5.2" ]; then
  pass "EPIC.md has spec_version: 0.5.2"
else
  fail "EPIC.md must declare spec_version: 0.5.2 for this operational profile"
fi

if [ "$EPIC_ID" = "$EPIC_NAME" ]; then
  pass "EPIC.md id matches the directory name"
else
  fail "EPIC.md id must match the directory name"
fi

section "EPIC.md body"
require_heading "$EPIC_PATH" "Objective"
require_heading "$EPIC_PATH" "Phases"
require_heading "$EPIC_PATH" "Success criteria"
require_heading "$EPIC_PATH" "State to preserve"
require_heading "$EPIC_PATH" "Guardrails"
require_heading "$EPIC_PATH" "Resume"

section "runtime/state.json"
STATE_PATH="$EPIC_DIR/runtime/state.json"
CURRENT_PLAN=""
if [ -f "$STATE_PATH" ]; then
  if python3 - "$STATE_PATH" <<'PY'
import json, sys
path = sys.argv[1]
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)
required = ["state_version", "status", "current_plan"]
missing = [key for key in required if key not in data]
if missing:
    print(",".join(missing))
    raise SystemExit(1)
if data["status"] not in {"active", "paused", "complete", "abandoned"}:
    print(data["status"])
    raise SystemExit(2)
PY
  then
    CURRENT_PLAN=$(python3 - "$STATE_PATH" <<'PY'
import json, sys
with open(sys.argv[1], "r", encoding="utf-8") as f:
    print(json.load(f)["current_plan"])
PY
)
    pass "runtime/state.json is valid JSON and includes reserved fields"
  else
    fail "runtime/state.json must be valid JSON with state_version, status, and current_plan"
  fi
fi

section "runtime/plans"
PLANS_DIR="$EPIC_DIR/runtime/plans"
if [ -d "$PLANS_DIR" ]; then
  pass "runtime/plans exists"
else
  fail "runtime/plans is missing"
fi

shopt -s nullglob
PLAN_FILES=("$PLANS_DIR"/*.md)
shopt -u nullglob
if [ "${#PLAN_FILES[@]}" -gt 0 ]; then
  pass "runtime/plans contains at least one markdown plan"
else
  fail "runtime/plans must contain at least one markdown plan"
fi

for plan in "${PLAN_FILES[@]}"; do
  if grep -Eq "^Updated:" "$plan"; then
    pass "$(basename "$plan") has an Updated line"
  else
    warn "$(basename "$plan") should include an Updated line"
  fi

  if grep -Eq "^##[[:space:]]+Now([[:space:]]|$)" "$plan"; then
    pass "$(basename "$plan") has ## Now"
  else
    fail "$(basename "$plan") is missing ## Now"
  fi

  if grep -Eq "^##[[:space:]]+Next([[:space:]]|$)" "$plan"; then
    pass "$(basename "$plan") has ## Next"
  else
    fail "$(basename "$plan") is missing ## Next"
  fi

  if grep -Eq "^##[[:space:]]+Blocked([[:space:]]|$)" "$plan"; then
    pass "$(basename "$plan") has ## Blocked"
  else
    fail "$(basename "$plan") is missing ## Blocked"
  fi
done

section "runtime/log"
if [ -d "$EPIC_DIR/runtime/log" ]; then
  pass "runtime/log exists"
else
  fail "runtime/log is missing"
fi

section "hooks"
HOOKS_DIR="$EPIC_DIR/hooks"
HOOK_INSTALL="$EPIC_DIR/hooks/install.md"
HOOK_STATUS="$EPIC_DIR/hooks/status-changed.md"

if [ -d "$HOOKS_DIR" ]; then
  pass "hooks exists"
else
  fail "hooks is missing"
fi

if [ -f "$HOOK_INSTALL" ]; then
  pass "hooks/install.md exists"
else
  fail "hooks/install.md is missing"
fi

if [ -f "$HOOK_STATUS" ]; then
  pass "hooks/status-changed.md exists"
else
  warn "hooks/status-changed.md is recommended for the operational profile"
fi

shopt -s nullglob
HOOK_FILES=("$HOOKS_DIR"/*.md)
shopt -u nullglob
for hook_file in "${HOOK_FILES[@]}"; do
  hook_name=$(basename "$hook_file")
  if grep -Eq '^---$' "$hook_file"; then
    pass "$hook_name includes frontmatter"
  else
    fail "$hook_name is missing frontmatter"
  fi

  if grep -Eq '^type:[[:space:]]+(prompt|agent)' "$hook_file"; then
    pass "$hook_name declares a supported markdown hook type"
  else
    fail "$hook_name must declare type: prompt or type: agent in frontmatter"
  fi
done

section "cron.d"
if [ -d "$EPIC_DIR/cron.d" ]; then
  pass "cron.d exists"
  shopt -s nullglob
  CRON_FILES=("$EPIC_DIR"/cron.d/*.yml "$EPIC_DIR"/cron.d/*.yaml)
  shopt -u nullglob
  if [ "${#CRON_FILES[@]}" -eq 0 ]; then
    warn "cron.d exists but contains no YAML jobs"
  fi
  for cron_file in "${CRON_FILES[@]}"; do
    for field in name schedule timezone enabled run:; do
      if grep -Eq "^${field}" "$cron_file"; then
        pass "$(basename "$cron_file") includes ${field}"
      else
        fail "$(basename "$cron_file") is missing ${field}"
      fi
    done

    if grep -Eq '^[[:space:]]+type:[[:space:]]+(prompt|script|both)' "$cron_file"; then
      pass "$(basename "$cron_file") declares a supported run.type"
    else
      fail "$(basename "$cron_file") must declare run.type as prompt, script, or both"
    fi
  done
else
  warn "cron.d is absent"
fi

section "policy.yml"
POLICY_PATH="$EPIC_DIR/policy.yml"
if [ -f "$POLICY_PATH" ]; then
  pass "policy.yml exists"
  if grep -Eq '^autonomy:' "$POLICY_PATH"; then
    pass "policy.yml includes autonomy"
  else
    fail "policy.yml is missing autonomy"
  fi

  if grep -Eq '^escalation:' "$POLICY_PATH"; then
    pass "policy.yml includes escalation"
  else
    fail "policy.yml is missing escalation"
  fi
else
  fail "policy.yml is missing"
fi

section "Cross-file consistency"
if [ -n "$NAME_FIELD" ] && [ "$NAME_FIELD" = "$EPIC_NAME" ]; then
  pass "SKILL.md name matches the directory name"
else
  fail "SKILL.md name must match the directory name"
fi

if [ -n "$CURRENT_PLAN" ] && [ -f "$PLANS_DIR/$CURRENT_PLAN" ]; then
  pass "current_plan points to an existing plan file"
else
  fail "current_plan must point to an existing plan file in runtime/plans"
fi

if grep -Fq "runtime/" "$EPIC_PATH" && grep -Fq "runtime/" "$SKILL_PATH"; then
  pass "EPIC.md and SKILL.md both reference runtime paths"
else
  warn "EPIC.md and SKILL.md should both reference runtime paths"
fi

printf '\nSummary\n'
printf '  Epic: %s\n' "$EPIC_NAME"
printf '  Checks: %s\n' "$CHECKS"
printf '  Passed: %s\n' "$PASSED"
printf '  Failed: %s\n' "$FAILED"
printf '  Warnings: %s\n' "$WARNINGS"

if [ "$FAILED" -gt 0 ]; then
  printf '\nOperational epic profile validation failed.\n'
  exit 1
fi

printf '\nOperational epic profile is valid.\n'
